
version: "3"
services:

    sphinx:
        image: duzun/sphinx:2.2
        build: sphinx
        container_name: sphinx
        restart: always
        # env_file: .env
        # depends_on:
        #     - mariadb
        # external_links:
        #     - mariadb:db
        ports:
            - "9312:9312"
            - "9306:9306"
        volumes:
            # expose sphinx daemon to system through socket
            - /run/sphinx/:/run/sphinx/
            # make MySQL accessible to sphinx through socket
            - /run/mysqld/:/run/mysqld/
            # expose logs to host system
            - /var/log/sphinxsearch:/var/lib/sphinx/log
            # choose a location for index data
            # - /var/lib/sphinx/data:/var/lib/sphinx/data
